BCrowley_Website/templates/BCrowley_App/BCrowley_Website/BCrowley_App/urls.py
from django.conf.urls import url
from . import views

app_name = 'BCrowley_App'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ideas', views.ideas, name='ideas'),
    url(r'^inspiration', views.inspiration, name='inspiration'),
    url(r'^lists', views.lists, name='lists'),
    url(r'^projects', views.projects, name='projects'),
]

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/BCrowley_Website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from BCrowley_App import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^BCrowley_App/', include('BCrowley_App.urls')),
    url(r'^admin/', admin.site.urls),
]

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/BCrowley_App/models.py
from django.db import models

# Create your models here.
class Media(models.Model):
    BOOK = 'BK'
    MOVIE = 'MV'
    MUSIC = 'MS'
    ARTICLE = 'AT'

    ONESTAR = 1
    TWOSTARS = 2
    THREESTARS = 3
    FOURSTARS = 4
    FIVESTARS = 5

    TYPE_CHOICES = (
    (BOOK, 'Book'),
    (MOVIE, 'Movie'),
    (MUSIC, 'Music'),
    (ARTICLE, 'Article'),
    )

    RATING_CHOICES = (
    (ONESTAR, 1),
    (TWOSTARS, 2),
    (THREESTARS, 3),
    (FOURSTARS, 4),
    (FIVESTARS, 5),
    )

    med_type = models.CharField(max_length=264,unique=False,choices=TYPE_CHOICES)
    id_name = models.CharField(max_length=264,unique=False)
    title = models.CharField(max_length=264,unique=False)
    author = models.CharField(max_length=264,unique=False)
    cover_photo = models.URLField(max_length=264,unique=False)
    online_reference = models.URLField(max_length=264,unique=False)
    rating = models.IntegerField(unique=False,choices=RATING_CHOICES)
    review = models.TextField(unique=False)

    def __str__(self):
        return self.title

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/BCrowley_App/views.py
from django.shortcuts import render
from BCrowley_App.models import Media

# Create your views here.
def index(request):
    return render(request, 'BCrowley_App/index.html')

def ideas(request):
    return render(request, 'BCrowley_App/ideas.html')

def inspiration(request):
    return render(request, 'BCrowley_App/inspiration.html')

def lists(request):
    book_records = Media.objects.filter(med_type="BK").order_by('title')
    movie_records = Media.objects.filter(med_type="MV").order_by('title')
    music_records = Media.objects.filter(med_type="MS").order_by('title')
    article_records = Media.objects.filter(med_type="AT").order_by('title')

    media_dict = {'book_list':book_records, 'movie_list':movie_records, 'music_list':music_records, 'article_list':article_records}
    return render(request, 'BCrowley_App/lists.html', context=media_dict)

def projects(request):
    return render(request, 'BCrowley_App/projects.html')

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/templates/BCrowley_App/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <title>Brett Crowley</title>

    <!-- Links -->

      <link rel="icon" href="home/brettcrowley77/bcrowley-website/Personal_Website/static/img/favicon1.ico" type="image/x-icon" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link href="{% static "venobox/venobox.css" %}" type="text/css" rel="stylesheet" media="screen" />
    <link href="{% static "css/styles.css" %}" type="text/css" rel="stylesheet">
    <link href="{% static "css/layout.css" %}" type="text/css" rel="stylesheet">

    <!-- Metadata -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Brett Crowley's personal web site">
    <meta name="robots" content="noindex">
    <meta http-equiv="author" content="Brett Crowley">
    <meta http-equiv="pragma" content="no-cache">

  </head>
  <body>
    <!-- Navigation bar -->
    <nav id='topnav' class="navbar navbar-expand-lg fixed-top">
      <a class="navbar-brand" href="{% url 'BCrowley_App:index' %}">Brett Crowley</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'BCrowley_App:lists' %}">Lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'BCrowley_App:projects' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'BCrowley_App:inspiration' %}">Inspiration</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'BCrowley_App:ideas' %}">Ideas</a>
          </li>
        </ul>
      </div>
    </nav>
    {% block body_block %}

    {%  endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="{% static "venobox/venobox.js" %}" type="text/javascript"></script>
    <script src="{% static "javascript/mainscript.js" %}" type="text/javascript"></script>
  </body>
  <footer>
    <nav id="contactinfo" class="navbar navbar-expand-lg fixed-bottom">
      <div class='row'>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item col-lg-6 col-md-6 col-sm-6 col-xs-6"><a id='emailaddress' class="nav-link" href="#">brettcrowley77@gmail.com</a></li>
        </ul>
      </div>
    </nav>
  </footer>
</html>

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/templates/BCrowley_App/ideas.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Ideas</title>
  </head>
  <body>

  </body>
</html>

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/templates/BCrowley_App/index.html
<!DOCTYPE html>
{% extends "BCrowley_App/base.html" %}
{% block body_block %}
{% load staticfiles %}
    <!-- Welcome container -->
    <div class='container'>
      <div id='welcome' class='jumbotron framed'>
        <div class='row'>
            <div id='profile' class='col-lg-6 col-sm-12'><img class='profileslide framed' src="{% static "img/profile1.jpg" %}"></div>
    	    <div id='bio' class='col-lg-6 col-sm-12'>
    				<h1 class='category'>Welcome to my personal web site.</h1>
    				<p>I am a curiously-minded civil engineering graduate, competitive distance runner,
              avid reader and aspiring computer programmer. This site is a place for me to share some of my favourite
              things, in the hope that they might be as meaningful to others as they have been to me.</p>
    			</div>
        </div>
      </div>
		</div>
    <!-- Current container -->
	<div id='current' class='container'>
        <div class= "row">
            <div id="currentread" class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
              <div class='showcase'>
                <h2 class='category'>Currently reading</h2>
                <a class="venobox_custom" data-vbtype="inline" href="#happinessisachoice"><img src='http://t1.gstatic.com/images?q=tbn:ANd9GcRx7dTrNVi3swpxha6KUdpLwrMb5gC51ZSd8zNErJ2i2mpKDKID' alt='Happiness Is A Choice You Make by John Leland' class='center framed'></a>
                  <div id="happinessisachoice" class="nodisplay">
                      <div class="row">
                        <div class='column col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                          <img src='http://t1.gstatic.com/images?q=tbn:ANd9GcRx7dTrNVi3swpxha6KUdpLwrMb5gC51ZSd8zNErJ2i2mpKDKID' alt='Happiness Is A Choice You Make by John Leland' class='reviewpic center'>
                        </div>
                        <div class='column col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                          <div class="reviewtext center">
                            <h1 class='category'>My rating: <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></h1><br />
                            <h2 class='category'><a href="https://www.goodreads.com/book/show/35259558-happiness-is-a-choice-you-make" target='_blank'>Find it on Goodreads</a></h2>
                            <p></p>
                          </div>
                        </div>
                      </div>
                  </div>
              </div>
            </div>
            <div id="currentproject" class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
              <div class='showcase'>
                <h2 class='category'>Current project</h2>
                <p class='middle'>My current project is making this website. I'm taking a Udemy course on Full-Stack development to guide my learning.</p>
              </div>
            </div>
      		<div id="recentpost" class='column col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                <div class='showcase'>
                    <h2 class='category'>Latest post</h2>
                        <div class='iframe-container framed'>
                            <iframe src='https://brettcrowley77.wordpress.com/2018/02/04/the-glory-of-the-small/' allowfullscreen="" scrolling="yes" seamless="seamless"></iframe>
                        </div>
                </div>
            </div>
	    </div>
    </div>
{% endblock %}

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/templates/BCrowley_App/inspiration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Inspiration</title>
  </head>
  <body>

  </body>
</html>

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/templates/BCrowley_App/lists.html
<!DOCTYPE html>
{% extends "BCrowley_App/base.html" %}
{% block body_block %}
{% load staticfiles %}
<div id="library" class="container">

  <div id="lists" class="row">
    <div id="books" class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <h2 class="category"><i class="fas fa-book"></i> Books</h2>
      </div>
    </div>
    <div id="movies" class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <h2 class="category"><i class="fas fa-film"></i> Movies</h2>
      </div>
    </div>
    <div id="music" class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <h2 class="category"><i class="fas fa-music"></i> Music</h2>
      </div>
    </div>
    <div id="articles" class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <h2 class="category"><i class="far fa-newspaper"></i> Articles</h2>
      </div>
    </div>
  </div>

  <!-- Book shelf contents -->
  <div id="bookshelf" class= "row hide">

    {% if book_list %}
    {% for book in book_list %}
    <div class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <a class="venobox_custom" data-vbtype="inline" data-gall="myGallery" href="#{{book.id_name}}"><img src='{{book.cover_photo}}' alt='{{book.title}} by {{book.author}}' class='center framed'></a>
          <div id="{{book.id_name}}" class="nodisplay">
              <div class="row">
                <div class='column col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                  <img src='{{book.cover_photo}}' alt='{{book.title}} by {{book.author}}' class='reviewpic center'>
                </div>
                <div class='column col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                  <div class="reviewtext center">
                    <h1 class='category'>My rating:
                      {% for num in '012345' %}
                      {% if forloop.counter0 < book.rating %}
                      <i class="fas fa-star"></i>
                      {% endif %}
                      {% endfor %}
                    </h1><br />
                    <h2 class='category'><a href="{{book.online_reference}}" target='_blank'>Find it on Goodreads</a></h2>
                    <p>{{book.review}}</p>
                  </div>
                </div>
              </div>
          </div>
        <p>
          {% for num in '012345' %}
          {% if forloop.counter0 < book.rating %}
          <i class="fas fa-star"></i>
          {% endif %}
          {% endfor %}
        </p>
      </div>
    </div>
    {% endfor%}
    {% else %}
      <p>No books found!</p>
    {% endif %}
  </div>

  <!-- Movie shelf contents -->
  <div id="movieshelf" class= "row hide">
    {% if movie_list %}
    {% for movie in movie_list %}
    <div class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <a class="venobox" data-autoplay="true" data-vbtype="video" data-gall="myGallery" href='{{movie.online_reference}}' target='_blank'><img src='{{movie.cover_photo}}' alt='{{movie.title}}' class='center framed'></a>
        <p>
          {% for num in '012345' %}
          {% if forloop.counter0 < movie.rating %}
          <i class="fas fa-star"></i>
          {% endif %}
          {% endfor %}
        </p>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  <!-- Music shelf contents -->
  <div id="musicshelf" class= "row hide">
    {% if music_list %}
    {% for music in music_list %}
    <div class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <a class="venobox" data-autoplay="true" data-vbtype="video" data-gall="myGallery" href='{{music.online_reference}}' target='_blank'><img src='{{music.cover_photo}}' alt='{{music.title}}' class='center framed'></a>
        <p><em>{{music.title}}</em>, by {{music.author}}</p>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  <!-- Article shelf contents -->
  <div id="articleshelf" class= "row hide">
    {% if article_list %}
    {% for article in article_list %}
    <div class='column col-lg-3 col-md-3 col-sm-6 col-xs-12'>
      <div class='showcase'>
        <a href='{{article.online_reference}}' target='_blank'><img src='{{article.cover_photo}}' alt='{{article.title}}' class='center framed'></a>
        <p><em>{{article.title}}</em>, by {{article.author}}</p>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>

</div>
{% endblock %}

BCrowley_Website/templates/BCrowley_App/BCrowley_Website/templates/BCrowley_App/projects.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Projects</title>
  </head>
  <body>

  </body>
</html>